language: python
python: 3.5

install:
  - pip3 install codecov pycodestyle

script:
  - pip3 install -r requirements.txt
  - coverage run --source=montagu setup.py test
  - pycodestyle montagu test

after_success:
  - codecov

services:
  - docker
